Tested locally with {{3.11}} and works fine:
{noformat}
$ pytest --count=10 --cassandra-dir=~/ws/cassandra thrift_hsha_test.py::TestThriftHSHA::test_closing_connections
=================================================================================================================================== test session starts ===================================================================================================================================
platform darwin -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/zjay/ws/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.2.1, repeat-0.5.0, flaky-3.4.0
timeout: 900.0s method: signal
collected 10 items

thrift_hsha_test.py ..........                                                                                                                                                                                                                                                      [100%]
===Flaky Test Report===

test_closing_connections[1/10] passed 1 out of the required 1 times. Success!
test_closing_connections[2/10] passed 1 out of the required 1 times. Success!
test_closing_connections[3/10] passed 1 out of the required 1 times. Success!
test_closing_connections[4/10] passed 1 out of the required 1 times. Success!
test_closing_connections[5/10] passed 1 out of the required 1 times. Success!
test_closing_connections[6/10] passed 1 out of the required 1 times. Success!
test_closing_connections[7/10] passed 1 out of the required 1 times. Success!
test_closing_connections[8/10] passed 1 out of the required 1 times. Success!
test_closing_connections[9/10] passed 1 out of the required 1 times. Success!
test_closing_connections[10/10] passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

=============================================================================================================================== 10 passed in 446.70 seconds ===============================================================================================================================
{noformat}

[~jay.zhuang] hmm, I ended up running it locally, as well, for about 30 times, and no fail.

However, looking at the error, this jumps out:

{noformat}
Subprocess ['nodetool', '-h', 'localhost', '-p', '7100', 'enablethrift']
{noformat}

In the dtest, we [invoke enablethrift|https://github.com/apache/cassandra-dtest/blob/master/thrift_hsha_test.py#L72] immediately after disabling thrift. It could be that the socket isn't totally free yet on the various CI servers, and hence why we get the {{Could not create ServerSocket on address /127.0.0.1:9160}} message. (I'm assuming that's problem binding to the port, 9160; haven't read thrift source in years).

I have a trivial patch and circlci job going now: https://circleci.com/gh/jasobrown/workflows/cassandra/tree/14595-3.0. Will see if anything comes happens.

Nope, naive sleep() didn't seem to fix it. Will have to figure out what's really going wrong, i guess ...

Reproduced this [here|https://app.circleci.com/pipelines/github/maedhroz/cassandra/24/workflows/f61eecd1-73c2-40e0-ba39-05c1d5c8ad01/jobs/190].

