This behavior has recently appeared in some environments. TC also has the same [issue|https://ci.ignite.apache.org/buildConfiguration/ApacheIgnite3xGradle_Test_RunAllTests/7559849?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandCode+Inspection=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true].

The placement driver correctly started, and the active actor was also ready, but for some reason, no lease was created. The result is the timeout exception for waiting for a primary replica through the API.

{noformat}
2023-10-15T23:37:32,477][INFO ][%iinrt_nwdt_0%JRaft-ReadOnlyService-Disruptor-_stripe_8-0][AssignmentsTracker] Assignment cache initialized for placement driver [groupAssignments={}]
[2023-10-15T23:37:32,478][INFO ][%iinrt_nwdt_0%JRaft-ReadOnlyService-Disruptor-_stripe_8-0][TopologyTracker] Logical topology initialized for placement driver [topologySnap=LogicalTopologySnapshot [version=0, nodes=SetN []]]
[2023-10-15T23:37:32,483][INFO ][%iinrt_nwdt_0%Raft-Group-Client-1][PlacementDriverManager] Placement driver active actor is starting.
...

Caused by: org.apache.ignite.internal.placementdriver.PrimaryReplicaAwaitTimeoutException: IGN-PLACEMENTDRIVER-1 TraceId:c085cfe8-570c-4947-a4b6-ed7c3fea041d The primary replica await timed out [replicationGroupId=4_part_0, referenceTimestamp=HybridTimestamp [time=111240718117240832, physical=1697398652912, logical=0], currentLease=null]
	at org.apache.ignite.internal.placementdriver.leases.LeaseTracker.lambda$awaitPrimaryReplica$2(LeaseTracker.java:229)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2792)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	... 3 more
Caused by: java.util.concurrent.TimeoutException
	... 7 more
{noformat}

