This test failed in one of the recent [GVO builds|https://jenkins.impala.io/job/ubuntu-16.04-dockerised-tests/4902/]:
Stacktrace:
{noformat}
metadata/test_show_create_table.py:64: in test_show_create_table
    unique_database)
metadata/test_show_create_table.py:127: in __run_show_create_table_test_case
    result = self.__exec(test_case.show_create_table_sql)
metadata/test_show_create_table.py:135: in __exec
    return self.execute_query_expect_success(self.client, sql_str)
common/impala_test_suite.py:831: in wrapper
    return function(*args, **kwargs)
common/impala_test_suite.py:839: in execute_query_expect_success
    result = cls.__execute_query(impalad_client, query, query_options, user)
common/impala_test_suite.py:956: in __execute_query
    return impalad_client.execute(query, user=user)
common/impala_connection.py:212: in execute
    return self.__beeswax_client.execute(sql_stmt, user=user)
beeswax/impala_beeswax.py:189: in execute
    handle = self.__execute_query(query_string.strip(), user=user)
beeswax/impala_beeswax.py:365: in __execute_query
    handle = self.execute_query_async(query_string, user=user)
beeswax/impala_beeswax.py:359: in execute_query_async
    handle = self.__do_rpc(lambda: self.imp_service.query(query,))
beeswax/impala_beeswax.py:522: in __do_rpc
    raise ImpalaBeeswaxException(self.__build_error_message(b), b)
E   ImpalaBeeswaxException: ImpalaBeeswaxException:
E    INNER EXCEPTION: <class 'beeswaxd.ttypes.BeeswaxException'>
E    MESSAGE: AnalysisException: org.apache.impala.catalog.TableLoadingException: Error opening Iceberg table 'test_show_create_table_8b557a01.iceberg_ctas'
E   CAUSED BY: TableLoadingException: Error opening Iceberg table 'test_show_create_table_8b557a01.iceberg_ctas'
E   CAUSED BY: InconsistentMetadataFetchException: Catalog object TCatalogObject(type:TABLE, catalog_version:6846, table:TTable(db_name:test_show_create_table_8b557a01, tbl_name:iceberg_ctas)) changed version between accesses.
{noformat}

Reached out to Zoltan about this and he mentioned that this is probably due to a failure to detect a self-event on an iceberg table which resulted in a change to the catalog version of the table during some operation.