The test of [test_query_cancellation_during_wait_to_finish|https://github.com/apache/impala/blob/master/tests/shell/test_shell_commandline.py#L395-L403] failed in a recent build with the following error message.
{code:java}
Exception: The found in flight query is not the one under test: set all
{code}
The error message was produced at [https://github.com/apache/impala/blame/master/tests/shell/test_shell_commandline.py#L418] in {{wait_for_query_state()}}, which is authored by [~gaborkaszab]. Maybe you could offer some insight into it? Assign the JIRA to you for now but please feel free to assign it to other as you see appropriate. Tagged [~tarmstrong]  here since Tim also helped with reviewing the patch ([https://gerrit.cloudera.org/c/8713/]). Thanks!

 