Saw TestLoadDataExternal.test_load failed in an unrelated patch:
[https://jenkins.impala.io/job/ubuntu-16.04-dockerised-tests/6774/]

{code}
metadata.test_load.TestLoadData.test_load[protocol: beeswax | exec_option: {'test_replan': 1, 'batch_size': 0, 'num_nodes': 0, 'disable_codegen_rows_threshold': 5000, 'disable_codegen': False, 'abort_on_error': 1, 'exec_single_node_rows_threshold': 0} | table_format: text/none] (from pytest)
{code}

Stacktrace
{noformat}
metadata/test_load.py:106: in test_load
    self.run_test_case('QueryTest/load', vector)
common/impala_test_suite.py:711: in run_test_case
    result = exec_fn(query, user=test_section.get('USER', '').strip() or None)
common/impala_test_suite.py:649: in __exec_in_impala
    result = self.__execute_query(target_impalad_client, query, user=user)
common/impala_test_suite.py:985: in __execute_query
    return impalad_client.execute(query, user=user)
common/impala_connection.py:212: in execute
    return self.__beeswax_client.execute(sql_stmt, user=user)
beeswax/impala_beeswax.py:189: in execute
    handle = self.__execute_query(query_string.strip(), user=user)
beeswax/impala_beeswax.py:365: in __execute_query
    handle = self.execute_query_async(query_string, user=user)
beeswax/impala_beeswax.py:359: in execute_query_async
    handle = self.__do_rpc(lambda: self.imp_service.query(query,))
beeswax/impala_beeswax.py:522: in __do_rpc
    raise ImpalaBeeswaxException(self.__build_error_message(b), b)
E   ImpalaBeeswaxException: ImpalaBeeswaxException:
E    INNER EXCEPTION: <class 'beeswaxd.ttypes.BeeswaxException'>
E    MESSAGE: AnalysisException: Could not resolve table reference: 'functional.test_load_nopart'
{noformat}

In the coordinator logs, I can see two different tests using the same table name 'functional.test_load_nopart'. Their identifiers:
{code}
  74: client_identifier (string) = "metadata/test_load.py::TestLoadData::()::test_load[protocol:beeswax|exec_option:{'test_replan':1;'batch_size':0;'num_nodes':0;'disable_codegen_rows_threshold':5000;'disable_codegen':False;'abort_on_error':1;'exec_single_node_rows_threshold':0}|table_forma",

  74: client_identifier (string) = "metadata/test_load.py::TestLoadDataExternal::()::test_load[protocol:beeswax|exec_option:{'test_replan':1;'batch_size':0;'num_nodes':0;'disable_codegen_rows_threshold':5000;'disable_codegen':False;'abort_on_error':1;'exec_single_node_rows_threshold':0}|tab"
{code}
I think they should use different databases to avoid impacting each other.