[~stakiar], assign this to you since you have background on this. Feel free to reassign it if you don't have enough bandwidth. Thanks!

Saw same error in recent run.

saw this error in test hs2.test_fetch_first.TestFetchFirst.test_query_stmts_v1

Commit 4502097a2d6bc9d41da185762d231f7fe413224b in impala's branch refs/heads/master from Sahil Takiar
[ https://gitbox.apache.org/repos/asf?p=impala.git;h=4502097 ]

IMPALA-9799: Add retries to TestFetchFirst get_num_in_flight_queries calls

The calls to get_num_in_flight_queries in TestFetchFirst are flaky
because they expect the number of in flight queries to drop to 0
immediately. This might not always be true, especially in ASAN builds
where Impala is generally slower.

This patch wraps to call to get_num_in_flight_queries in
ImpalaTestSuite.assert_eventually, which adds retries to the calls to
get_num_in_flight_queries.

Testing:
* Ran tests/hs2/test_fetch_first.py locally

Change-Id: I349f861e8219e62311e8d4e0bfbd8f3618f0fa46
Reviewed-on: http://gerrit.cloudera.org:8080/16218
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>


Saw this again in

 [https://master-02.jenkins.cloudera.com/job/impala-cdpd-master-core-asan/456/]

Stacktrace:
{code:java}
/data/jenkins/workspace/impala-cdpd-master-core-asan/repos/Impala/tests/hs2/hs2_test_suite.py:63: in add_session
    lambda: fn(self))
/data/jenkins/workspace/impala-cdpd-master-core-asan/repos/Impala/tests/hs2/hs2_test_suite.py:44: in add_session_helper
    fn()
/data/jenkins/workspace/impala-cdpd-master-core-asan/repos/Impala/tests/hs2/hs2_test_suite.py:63: in <lambda>
    lambda: fn(self))
/data/jenkins/workspace/impala-cdpd-master-core-asan/repos/Impala/tests/hs2/test_fetch_first.py:120: in test_query_stmts_v6_with_result_spooling
    self.run_query_stmts_test({'spool_query_results': 'true'})
/data/jenkins/workspace/impala-cdpd-master-core-asan/repos/Impala/tests/hs2/test_fetch_first.py:181: in run_query_stmts_test
    self.__test_invalid_result_caching("SELECT COUNT(*) FROM functional.alltypes")
/data/jenkins/workspace/impala-cdpd-master-core-asan/repos/Impala/tests/hs2/test_fetch_first.py:63: in __test_invalid_result_caching
    assert 0 == impalad.get_num_in_flight_queries()
E   assert 0 == 1
E    +  where 1 = <bound method ImpaladService.get_num_in_flight_queries of <tests.common.impala_service.ImpaladService object at 0x753fcd0>>()
E    +    where <bound method ImpaladService.get_num_in_flight_queries of <tests.common.impala_service.ImpaladService object at 0x753fcd0>> = <tests.common.impala_service.ImpaladService object at 0x753fcd0>.get_num_in_flight_queries
{code}

I'm going to just close this for now since it hasn't happened for a while. Please file a new JIRA if there is a similar failure.

