When stop on failure option is specified, pig abruptly exits without displaying any job stats or failed job information which it usually does in case of failures.

{code}
2015-06-04 20:35:38,170 [uber-SubtaskRunner] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher  - 9% complete
2015-06-04 20:35:38,171 [uber-SubtaskRunner] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher  - Running jobs are [job_1428329756093_3741748,job_1428329756093_3741752,job_1428329756093_3741753,job_1428329756093_3741754,job_1428329756093_3741756]
2015-06-04 20:35:40,201 [uber-SubtaskRunner] ERROR org.apache.pig.tools.grunt.Grunt  - ERROR 6017: Job failed!
Hadoop Job IDs executed by Pig: job_1428329756093_3739816,job_1428329756093_3741752,job_1428329756093_3739814,job_1428329756093_3741748,job_1428329756093_3741756,job_1428329756093_3741753,job_1428329756093_3741754

<<< Invocation of Main class completed <<<
{code}
